// Durable execution
export {
  workflow,
  flow,
  WorkflowBuilder,
  type Workflow,
  type IdempotencyConfig,
  type WorkflowHandle,
  type WorkflowStatusInfo,
  type WorkflowHooks,
  type WorkflowDAG,
  dagToMermaid,
  dagToDot,
  type StepContext,
  type DagStepContext,
  type MapStepContext,
  type StepOptions,
  type StepFailureStrategy,
  type WorkflowStorage,
  type FenceGuard,
  type FenceToken,
  type WorkflowOrderBy,
  type SignalTokenRecord,
  type StreamChunk,
  type StreamDescriptor,
  type StreamKind,
  type DefineStreamOptions,
  defineStream,
  defineInputStream,
  appendStreamChunk,
  appendExternalStreamChunk,
  peekStreamChunk,
  workflowMetadataMatches,
  type WorkflowState,
  type WorkflowSummary,
  type WorkflowRunSummary,
  type StepState,
  type StepTaskState,
  type SignalState,
  type WorkflowStatus,
  type StepStatus,
  type StepType,
  type RunSource,
  RUN_SOURCE_CODES,
  encodeRunSource,
  decodeRunSource,
  InMemoryWorkflowStorage,
  WorkflowVersionRegistry,
  ScopedWorkflowVersionRegistry,
  createWorkflowVersionRegistry,
  type WorkflowVersionRegistryConfig,
  type IWorkflowVersionRegistry,
  type VersionRecord,
  type VersionStatus,
  WorkflowError,
  StepError,
  StorageError,
  WorkflowLockError,
  WorkflowSuspendedError,
  WorkflowContinueAsNewError,
  WorkflowTimeoutError,
  StepTimeoutError,
  WorkflowDeadlineError,
  WorkflowVersionMismatchError,
  FenceTokenMismatchError,
  GuardError,
  WorkflowTripwireError,
  TripwireStorageMissingError,
  LoopLimitExceededError,
  MatchError,
  type MatchParams,
  topologicalSort,
  computeReadySet,
  type DagNode,
  DefaultWorkflowRunner,
  InProcessStepExecutor,
  createWorkflowRunner,
  RecoveryStrategy,
  RecoveryStrategyBuilder,
  type WorkflowRunner,
  type WorkflowRunnerConfig,
  type WorkflowRunnerRunParams,
  type WorkflowRunSafeError,
  type StepExecutor,
  type StepExecutionRequest,
  type StepExecutionResult,
  type RecoveryResult,
  type StaleTerminationAction,
  trigger,
  WorkflowResult,
  webhookTrigger,
  type WebhookTriggerConfig,
  type WebhookRequest,
  type WebhookHandler,
  type WebhookHmacConfig,
  type JournalEntry,
  type JournalStepType,
  type JournalPhase,
  type ActivityJournalStorage,
  type JournaledSuspendStorage,
  isActivityJournalStorage,
  isJournaledSuspendStorage,
  runJournaledStep,
  completeSignal,
  completeDueSleeps,
  invokeQueryHandler,
  hasQueryHandlers,
  listQueryHandlers,
  clearQueryHandlers,
  JournalNonDeterminismError,
  JournalStorageMissingError,
  type JournaledContext,
  type JournaledStepBody,
  type ActivityYield,
  type ActivityOptions,
  type CompensateConfig,
  type DispatchConfig,
  type CompensationStatus,
  type StepAttemptRecord,
  type StepAttemptType,
  type StepAttemptStorage,
  isStepAttemptStorage,
  type TripwireCapableStorage,
  isTripwireCapableStorage,
  type SubscribableStorage,
  isSubscribableStorage,
  type WorkflowRunEvent,
  type FailedWorkflowRecord,
  type WorkflowSchema,
  type StepSchema,
  type SingleStepSchema,
  type MapStepSchema,
  type StepSchemaOptions,
  type MapStepSchemaOptions,
  type JsonSchema,
  type NodeUiMeta,
  WorkflowSchemaZ,
  validateWorkflowSchema,
  validateWorkflowSchemaSafe,
  type ActivityRegistry,
  type ActivityFactory,
  type ActivityContext,
  MapActivityRegistry,
  compileWorkflow,
  WorkflowCompilationError,
  stateMachine,
  machine,
  pureStateMachine,
  StateMachineBuilder,
  StateMachineInstance,
  QuickMachineBuilder,
  MachineHandle,
  type PureStateMachineBuilder,
  EventDataValidationError,
  StateMachineVersionMismatchError,
  TIMEOUT_EVENT,
  type StateMachineStorage,
  InMemoryStateMachineStorage,
  type MachineSnapshot,
  type MachineState,
  type TransitionEvent,
  type ContextOf,
  type TransitionsOf,
  type EventsOf,
  type TerminalStates,
  type TransitionTo,
  transitionTo,
  type MachineLimits,
  type MachineMiddleware,
  type TransitionContext,
  type EventsMap,
  type EventData,
  type EventName,
  type SendParams,
  type StrictSchemas,
  composeMachineMiddleware,
  retryMiddleware as machineRetryMiddleware,
} from "./lib/durable/index.ts";

// Scheduler
export {
  type ScheduleConfig,
  type DurableScheduleConfig,
  type ScheduleTick,
  type Scheduler,
  type SchedulerStorage,
  isTickLogStorage,
  InMemoryScheduler,
  createScheduler,
  DurableScheduler,
  type DurableSchedulerConfig,
  createDurableScheduler,
  InMemorySchedulerStorage,
  computeDueTicks,
  computeNextRun,
  validateScheduleConfig,
  scheduleMetadataContains,
  flattenLeafPaths,
  scheduleTickRunId,
} from "./lib/scheduler/index.ts";

// Distributed workflow execution
export {
  type StepRegistry,
  type StepHandler,
  type StepRegistration,
  type WorkerStepOptions,
  MapStepRegistry,
  type StepQueue,
  type StepTask,
  type FairnessPolicy,
  InMemoryStepQueue,
  DistributedWorkflowRunner,
  createDistributedWorkflowRunner,
  type DistributedRunnerConfig,
  type WorkflowCoordinator,
  type CoordinatorConfig,
  DefaultCoordinator,
  createCoordinator,
  buildStubWorkflow,
  type WorkflowWorker,
  type WorkerConfig,
  type WorkerInfo,
  type WorkerStatus,
  type WorkerRegistry,
  InMemoryWorkerRegistry,
  type LeaderElection,
  SingleLeader,
  type SleepScanner,
  type SleepScannerConfig,
  DefaultSleepScanner,
  createSleepScanner,
  type SignalScanner,
  type SignalScannerConfig,
  DefaultSignalScanner,
  createSignalScanner,
  DefaultWorker,
  createWorker,
  type WorkerHooks,
  type WorkerMiddleware,
  type NextFn,
  timeoutMiddleware,
  retryMiddleware,
  loggingMiddleware,
  metricsMiddleware,
  StepQueueExecutor,
  type WorkflowAdvertisementRegistry,
  type AdvertisedWorkflow,
  type AdvertisementEntry,
  InMemoryWorkflowAdvertisementRegistry,
  workflowAdvertisementRegistryTestSuite,
  type WorkflowStartQueue,
  type WorkflowStartRecord,
  type WorkerWorkflowSpec,
  InMemoryWorkflowStartQueue,
  workflowStartQueueTestSuite,
} from "./lib/distributed/index.ts";

// SQL Models (dbt-style)
export {
  type SqlModel,
  type SqlProject,
  type SqlProjectResult,
  type Materialization,
  type ExpectationDef as SqlExpectationDef,
  compileSqlProject,
  type SqlCompilerConfig,
} from "./lib/sql-models/index.ts";

// Filesystem-based discovery — share a single configured scanner across
// the dashboard server and any worker / agent process that also imports
// workflow definitions from disk.
export {
  WorkflowScanner,
  ScheduleScanner,
  applyDiscoveredSchedules,
  type WorkflowScannerOptions,
  type WorkflowScanResult,
  type ScheduleScannerOptions,
  type ScheduleScanResult,
  type ApplyDiscoveredSchedulesOptions,
  type ApplyDiscoveredSchedulesResult,
} from "./lib/discovery/index.ts";

// Zero-dep JSON-Schema-native schema builder + validator. Used by
// `defineSignal` to type signal payloads and snapshot validation rules
// onto pending journal entries.
//
// `JsonSchema` (the tagged union the builder produces) is intentionally
// NOT re-exported at the top level — there's already a separate
// open-shape `JsonSchema` interface from `workflow-schema.ts` for
// workflow-IR I/O annotations. Callers pass through `someSig.schema.jsonSchema`
// (typed via `Schema<T>` structurally); deep-import from
// `./lib/schema/builder.ts` if you ever need to name the type.
export { s, type Schema, type OptionalSchema, type Infer } from "./lib/schema/builder.ts";
export { validate, type ValidationError, type ValidationResult } from "./lib/schema/validator.ts";

// First-class signal types — `defineSignal` returns an addressable
// artifact (name + schema) callers import wherever they suspend on /
// deliver to / inspect the signal. Mirrors how `tool({...})` works for
// tools. `approvalSignal` is the canonical preset over `ctx.signal` with
// the canonical approval shape and the `approve:` name prefix.
export {
  defineSignal,
  approvalSignal,
  ApprovalSchema,
  APPROVAL_NAME_PREFIX,
  type SignalType,
  type SignalPayload,
  type ApprovalDecision,
} from "./lib/signals/define-signal.ts";
