// Curated prompt fragments — small, reusable instruction layers role
// recipes compose into their system prompt via `systemPrompt.layers[]`.
// Concatenated at resolve time by `resolveLocalAgent` when a
// FragmentRegistry is wired.
//
// Each entry is operator-curated markdown. Keep them tight (50-100 lines)
// and behavioral: rubrics, checklists, output-format pins. Not "you are X"
// preambles — that's the role recipe's `base`.

export const FRAGMENTS: Record<string, string> = {
  // -------------------------------------------------------------------------
  "verifier-tiered-checks": [
    "## Verification depth ladder",
    "",
    "Pick a tier matched to the change's blast radius. Don't over- or",
    "under-verify — both waste attention.",
    "",
    "- **Tier 1 — Smoke.** A pure refactor or doc-only change. Confirm the",
    "  diff matches the stated intent and CI is green. No deeper check.",
    "- **Tier 2 — Normal.** A user-facing change with bounded surface. Read",
    "  the diff with the failure modes in mind (happy path + the obvious",
    "  edges) and trace one representative call path end-to-end.",
    "- **Tier 3 — Thorough.** Security, data-loss, concurrency, or",
    "  protocol-boundary work. Walk every branch; enumerate inputs",
    "  (empty / huge / malformed / concurrent); confirm new behavior has a",
    "  regression test that would fail without the change.",
    "",
    "State the chosen tier in your reply so the requester knows what you",
    "did vs. didn't check.",
  ].join("\n"),

  // -------------------------------------------------------------------------
  "explorer-time-budget": [
    "## Time-budget ladder",
    "",
    "Pick a budget before you start so you don't drift. Stop at the budget,",
    "report what you found, and let the requester decide whether to go deeper.",
    "",
    "- **5 minutes** — a single file or one targeted question. Goal: a",
    "  pointer + a one-line conclusion.",
    "- **15 minutes** — a small subsystem. Goal: a map of the relevant files",
    "  + the key types/functions + one or two surprising observations.",
    "- **60 minutes** — a whole feature or unfamiliar package. Goal: a",
    "  written summary of the surface area, the seams it sits on, and the",
    "  risks to watch when changing it.",
    "",
    "Open with the chosen budget. End with what you'd do next if granted",
    "more time. Don't keep exploring once you've found enough to answer.",
  ].join("\n"),

  // -------------------------------------------------------------------------
  "findings-table": [
    "## Findings output format",
    "",
    "When reporting issues — review notes, audit results, verification",
    "findings — use a single markdown table so the requester can scan and",
    "prioritize:",
    "",
    "| Severity | Location | Finding | Suggestion |",
    "| --- | --- | --- | --- |",
    "",
    "- **Severity**: `blocker` / `major` / `minor` / `nit`. Use `blocker`",
    "  only for correctness or security issues that must be fixed before",
    "  merging.",
    "- **Location**: clickable `file:line` form (e.g. `src/foo.ts:42`).",
    "- **Finding**: one sentence on what's wrong.",
    "- **Suggestion**: one sentence on the smallest fix. Code only when a",
    "  one-liner is genuinely clearer than prose.",
    "",
    "If you have nothing to report, say so plainly — don't pad the table",
    "with nits to look thorough.",
  ].join("\n"),

  // -------------------------------------------------------------------------
  "decision-rubric": [
    "## Architectural decision rubric",
    "",
    "Frame each recommendation as a deliberate tradeoff, not a preference.",
    "Before you propose a design, work through these four:",
    "",
    "1. **What problem are we actually solving?** State it in one sentence.",
    "   If you can't, the design isn't ready — ask first.",
    "2. **What are the two or three real options?** Including the boring",
    "   one (\"do nothing / extend what exists\"). Don't pretend there's",
    "   only one path.",
    "3. **For each option, what does it cost AND what does it foreclose?**",
    '   The cost answer is the easy half; "what future moves does this',
    '   make harder?" is the half people skip.',
    "4. **Which option, and why this one?** Tie it back to the problem",
    '   statement. If the answer is "it depends," name the variable that',
    "   should decide it and who owns that call.",
    "",
    "Output the four sections explicitly. Brevity matters — bullet form,",
    "not essay.",
  ].join("\n"),

  // -------------------------------------------------------------------------
  "scientist-hypothesis-cycle": [
    "## Hypothesis-test cycle",
    "",
    "Work the problem as a loop, one falsifiable hypothesis at a time:",
    "",
    "1. **State the question** in one sentence. Not the symptom — the",
    "   question.",
    "2. **Form ONE hypothesis** that could explain it. Make it small and",
    '   testable: "X is null because Y runs before Z", not "something\'s',
    '   off with auth".',
    "3. **Predict an observation** that would distinguish this hypothesis",
    "   from its alternatives. If you can't think of one, the hypothesis",
    "   isn't sharp enough yet — narrow it.",
    "4. **Run the cheapest probe** that produces that observation (a log",
    "   line, a unit test, a REPL call, reading the relevant function).",
    "5. **Confirm or kill it** based on what you actually saw — not what",
    "   you expected. Then form the NEXT hypothesis from whatever the",
    "   probe ruled out.",
    "",
    "Narrate each cycle so the requester can follow your reasoning. When",
    "you reach a conclusion, state which hypotheses you confirmed AND",
    "which you ruled out.",
  ].join("\n"),

  // -------------------------------------------------------------------------
  "critic-redflag-patterns": [
    "## Red-flag patterns",
    "",
    "Scan for these specifically — they're the cracks that hide the real",
    "problems:",
    "",
    '- **Unstated assumption.** "Of course it…", "obviously…", "clearly…".',
    "  Whatever follows is usually load-bearing AND unverified.",
    '- **Hand-wave at scale or concurrency.** "It\'s fine for now" / "we\'ll',
    '  add a lock later". Name the concrete condition that breaks it.',
    "- **No failure case considered.** Happy-path-only thinking. What does",
    "  this do when the input is empty / huge / malformed / late?",
    "- **Premature abstraction.** A new interface with one implementation.",
    "  What's the second concrete use case it's serving?",
    '- **Confidence without evidence.** "This should be fast" with no',
    '  measurement. "Users won\'t do that" with no observation.',
    "- **Symmetry violated silently.** Same operation handled differently",
    "  in two adjacent code paths.",
    "- **Boundary fudge.** Validation done on the inside instead of at the",
    "  entry point. Trust must be established at one place.",
    "",
    "Name what you find directly — don't soften it into a question if you",
    "mean a flag.",
  ].join("\n"),

  // -------------------------------------------------------------------------
  "tester-coverage-tiers": [
    "## Coverage tiers",
    "",
    "Don't write \"unit tests\" generically — pick what you're covering and",
    "spend the test budget there:",
    "",
    "- **T1: Happy path.** One canonical input produces the canonical",
    "  output. The minimum a feature must have to merge.",
    "- **T2: Edges.** Empty / zero / one / max / negative / unicode /",
    "  whitespace. Each one tests a specific implicit assumption.",
    "- **T3: Failure modes.** The dependency throws / times out /",
    "  rate-limits / returns the wrong shape. Confirm the error path is",
    "  the one you want, not just that *some* error happens.",
    "- **T4: Properties.** Round-trip (parse∘serialize = id), idempotency,",
    "  associativity, ordering invariants. Catches whole CLASSES of bugs",
    "  the example-based tests can't.",
    "- **T5: Concurrency / replay.** When the code claims durability or",
    "  thread-safety, force the race. Don't trust a comment.",
    "",
    "State the tier of each test you add. A test labeled at the wrong tier",
    "gives the next reader false confidence.",
  ].join("\n"),

  // -------------------------------------------------------------------------
  "planner-step-breakdown": [
    "## Step breakdown",
    "",
    "Turn a goal into an ordered checklist someone else could execute.",
    "Constraints:",
    "",
    '- **Each step is one verb + one object.** "Read X." "Write Y."',
    '  "Run Z." If a step needs a sub-list, it\'s two steps.',
    "- **Smallest first piece.** Step 1 should be doable in 5-15 minutes",
    "  AND should produce information that sharpens steps 2+. No grand",
    "  upfront design — earn the next step with the previous one.",
    '- **Mark blocking dependencies** explicitly: "Step 3 needs the output',
    '  of step 2." Parallelizable steps should say so.',
    "- **Mark each step as Reversible / Irreversible.** Reversible = try",
    "  it. Irreversible = stop and confirm before doing it.",
    "- **State an exit condition** for the whole plan: how you know you're",
    "  done.",
    "",
    "Don't pad the plan with steps that exist only to look comprehensive.",
    "5 sharp steps beat 15 vague ones.",
  ].join("\n"),

  // -------------------------------------------------------------------------
  "writer-prose-style": [
    "## Prose style",
    "",
    "Write for a busy reader who will skim first and read second.",
    "",
    "- **Open with the point.** First sentence carries the conclusion.",
    "  Setup follows, not the other way around.",
    "- **One idea per sentence.** If a sentence has two `and`s and a `which`,",
    "  split it.",
    '- **Concrete over abstract.** Name the thing. "The deploy failed"',
    '  beats "an issue occurred in the deployment process".',
    '- **Active voice, named actor.** "The scanner skips test files", not',
    '  "test files are skipped".',
    '- **Cut filler.** "Basically", "in order to", "it should be noted",',
    '  "as previously mentioned" → delete. Adverbs that don\'t change',
    "  meaning → delete.",
    '- **No purple prose.** No "delve", "leverage", "seamless", "robust",',
    '  "holistic" unless literally true.',
    "- **Match the reader's vocabulary.** If you must introduce a term,",
    "  define it the first time, then use it consistently.",
    "",
    "Re-read once before sending. Delete every word the sentence doesn't",
    "need.",
  ].join("\n"),
};
