// @ts-nocheck
import * as __fd_glob_58 from "../../content/docs/workflow/examples/06-state-machine.mdx?collection=docs"
import * as __fd_glob_57 from "../../content/docs/workflow/examples/05-batch-processing.mdx?collection=docs"
import * as __fd_glob_56 from "../../content/docs/workflow/examples/04-approval-with-signal.mdx?collection=docs"
import * as __fd_glob_55 from "../../content/docs/workflow/examples/03-priority-fairness.mdx?collection=docs"
import * as __fd_glob_54 from "../../content/docs/workflow/examples/03-bank-transfer-saga.mdx?collection=docs"
import * as __fd_glob_53 from "../../content/docs/workflow/examples/02-parallel-etl.mdx?collection=docs"
import * as __fd_glob_52 from "../../content/docs/workflow/examples/02-multi-queue-workers.mdx?collection=docs"
import * as __fd_glob_51 from "../../content/docs/workflow/examples/01-video-pipeline.mdx?collection=docs"
import * as __fd_glob_50 from "../../content/docs/workflow/examples/01-order-processing.mdx?collection=docs"
import * as __fd_glob_49 from "../../content/docs/topology/examples/03-distributed-shuffle.mdx?collection=docs"
import * as __fd_glob_48 from "../../content/docs/topology/examples/02-click-analytics.mdx?collection=docs"
import * as __fd_glob_47 from "../../content/docs/topology/examples/01-kafka-consume-produce.mdx?collection=docs"
import * as __fd_glob_46 from "../../content/docs/data/examples/06-sql-queries.mdx?collection=docs"
import * as __fd_glob_45 from "../../content/docs/data/examples/05-advanced-analytics.mdx?collection=docs"
import * as __fd_glob_44 from "../../content/docs/data/examples/04-streaming-etl.mdx?collection=docs"
import * as __fd_glob_43 from "../../content/docs/data/examples/03-sql-models.mdx?collection=docs"
import * as __fd_glob_42 from "../../content/docs/data/examples/02-data-quality.mdx?collection=docs"
import * as __fd_glob_41 from "../../content/docs/data/examples/01-analytics-query.mdx?collection=docs"
import * as __fd_glob_40 from "../../content/docs/core/examples/06-bulk-migration.mdx?collection=docs"
import * as __fd_glob_39 from "../../content/docs/core/examples/05-stream-etl.mdx?collection=docs"
import * as __fd_glob_38 from "../../content/docs/core/examples/04-race-providers.mdx?collection=docs"
import * as __fd_glob_37 from "../../content/docs/core/examples/03-data-pipelines.mdx?collection=docs"
import * as __fd_glob_36 from "../../content/docs/core/examples/03-circuit-breaker.mdx?collection=docs"
import * as __fd_glob_35 from "../../content/docs/core/examples/02-stream-composition.mdx?collection=docs"
import * as __fd_glob_34 from "../../content/docs/core/examples/02-parallel-fetches.mdx?collection=docs"
import * as __fd_glob_33 from "../../content/docs/core/examples/01-resilience.mdx?collection=docs"
import * as __fd_glob_32 from "../../content/docs/core/examples/01-fetch-with-retry.mdx?collection=docs"
import * as __fd_glob_31 from "../../content/docs/workflow/workflows.mdx?collection=docs"
import * as __fd_glob_30 from "../../content/docs/workflow/sql-models.mdx?collection=docs"
import * as __fd_glob_29 from "../../content/docs/workflow/scheduler.mdx?collection=docs"
import * as __fd_glob_28 from "../../content/docs/workflow/distributed-workers.mdx?collection=docs"
import * as __fd_glob_27 from "../../content/docs/topology/stream-topology.mdx?collection=docs"
import * as __fd_glob_26 from "../../content/docs/reference/patterns.mdx?collection=docs"
import * as __fd_glob_25 from "../../content/docs/reference/glossary.mdx?collection=docs"
import * as __fd_glob_24 from "../../content/docs/integrations/redis.mdx?collection=docs"
import * as __fd_glob_23 from "../../content/docs/integrations/postgres.mdx?collection=docs"
import * as __fd_glob_22 from "../../content/docs/integrations/kafka.mdx?collection=docs"
import * as __fd_glob_21 from "../../content/docs/integrations/http-client.mdx?collection=docs"
import * as __fd_glob_20 from "../../content/docs/getting-started/index.mdx?collection=docs"
import * as __fd_glob_19 from "../../content/docs/getting-started/comparison.mdx?collection=docs"
import * as __fd_glob_18 from "../../content/docs/data/quality.mdx?collection=docs"
import * as __fd_glob_17 from "../../content/docs/data/dataframe.mdx?collection=docs"
import * as __fd_glob_16 from "../../content/docs/core/stream-pipes.mdx?collection=docs"
import * as __fd_glob_15 from "../../content/docs/core/stream-pipeline.mdx?collection=docs"
import * as __fd_glob_14 from "../../content/docs/core/primitives.mdx?collection=docs"
import * as __fd_glob_13 from "../../content/docs/core/pipeline.mdx?collection=docs"
import * as __fd_glob_12 from "../../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_11 } from "../../content/docs/workflow/examples/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../../content/docs/topology/examples/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../../content/docs/data/examples/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../../content/docs/core/examples/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../../content/docs/workflow/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../../content/docs/topology/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../../content/docs/reference/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../../content/docs/integrations/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../../content/docs/data/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../../content/docs/core/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "../content/docs", {"meta.json": __fd_glob_0, "core/meta.json": __fd_glob_1, "data/meta.json": __fd_glob_2, "getting-started/meta.json": __fd_glob_3, "integrations/meta.json": __fd_glob_4, "reference/meta.json": __fd_glob_5, "topology/meta.json": __fd_glob_6, "workflow/meta.json": __fd_glob_7, "core/examples/meta.json": __fd_glob_8, "data/examples/meta.json": __fd_glob_9, "topology/examples/meta.json": __fd_glob_10, "workflow/examples/meta.json": __fd_glob_11, }, {"index.mdx": __fd_glob_12, "core/pipeline.mdx": __fd_glob_13, "core/primitives.mdx": __fd_glob_14, "core/stream-pipeline.mdx": __fd_glob_15, "core/stream-pipes.mdx": __fd_glob_16, "data/dataframe.mdx": __fd_glob_17, "data/quality.mdx": __fd_glob_18, "getting-started/comparison.mdx": __fd_glob_19, "getting-started/index.mdx": __fd_glob_20, "integrations/http-client.mdx": __fd_glob_21, "integrations/kafka.mdx": __fd_glob_22, "integrations/postgres.mdx": __fd_glob_23, "integrations/redis.mdx": __fd_glob_24, "reference/glossary.mdx": __fd_glob_25, "reference/patterns.mdx": __fd_glob_26, "topology/stream-topology.mdx": __fd_glob_27, "workflow/distributed-workers.mdx": __fd_glob_28, "workflow/scheduler.mdx": __fd_glob_29, "workflow/sql-models.mdx": __fd_glob_30, "workflow/workflows.mdx": __fd_glob_31, "core/examples/01-fetch-with-retry.mdx": __fd_glob_32, "core/examples/01-resilience.mdx": __fd_glob_33, "core/examples/02-parallel-fetches.mdx": __fd_glob_34, "core/examples/02-stream-composition.mdx": __fd_glob_35, "core/examples/03-circuit-breaker.mdx": __fd_glob_36, "core/examples/03-data-pipelines.mdx": __fd_glob_37, "core/examples/04-race-providers.mdx": __fd_glob_38, "core/examples/05-stream-etl.mdx": __fd_glob_39, "core/examples/06-bulk-migration.mdx": __fd_glob_40, "data/examples/01-analytics-query.mdx": __fd_glob_41, "data/examples/02-data-quality.mdx": __fd_glob_42, "data/examples/03-sql-models.mdx": __fd_glob_43, "data/examples/04-streaming-etl.mdx": __fd_glob_44, "data/examples/05-advanced-analytics.mdx": __fd_glob_45, "data/examples/06-sql-queries.mdx": __fd_glob_46, "topology/examples/01-kafka-consume-produce.mdx": __fd_glob_47, "topology/examples/02-click-analytics.mdx": __fd_glob_48, "topology/examples/03-distributed-shuffle.mdx": __fd_glob_49, "workflow/examples/01-order-processing.mdx": __fd_glob_50, "workflow/examples/01-video-pipeline.mdx": __fd_glob_51, "workflow/examples/02-multi-queue-workers.mdx": __fd_glob_52, "workflow/examples/02-parallel-etl.mdx": __fd_glob_53, "workflow/examples/03-bank-transfer-saga.mdx": __fd_glob_54, "workflow/examples/03-priority-fairness.mdx": __fd_glob_55, "workflow/examples/04-approval-with-signal.mdx": __fd_glob_56, "workflow/examples/05-batch-processing.mdx": __fd_glob_57, "workflow/examples/06-state-machine.mdx": __fd_glob_58, });