name: CI

on:
  push:
    branches-ignore:
      - main

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --no-cache

      - run: bunx nx run-many -t ci
